# s=set([1,2,3,4,])       #s from list
# print(s)
s = set()
s.add(40)
s.add(10)
s.add(20)
s.add(10)
s.add(30)
s.add(30)
print("s= ",s)
# print("type of s is",type(s))
s1=set([7,1,10,5,2,3,4,9,8,0])
print("s1= ",s1)
s2= s.union(s1)
print("s2= ",s2)
# # print(s.intersection(s1))
# print("Length of s is",len(s))
# print("Max value in s is",max(s))
# print("Min value in s is",min(s))
# print("Length of s1 is",len(s1))
# print("Max value in s1 is",max(s1))
# print("Min value in s1 is",min(s1))
# print("Length of s2 is",len(s2))
# print("Max value in s2 is",max(s2))
# print("Min value in s2 is",min(s2))