# S="Hello"
S="hello, howareyou"
# print(len(S))
# print(type(S))
# print(S[:2])
print(S[::-1])
# print(S[0:13:3])
# print(S[0:(len(S)-1)])
# print(S.isalnum())
# print(S.isalpha())
# print(S.endswith('you'))
# print(S.count('l'))
# print(S.capitalize())
# print(S.lower())
# print(S.upper())
# print(S.find('o'))
# var = S.replace('are', "is")
# print(var)
# z = list(S)
# print(z)
print(S)